let tv='tools';
const BRIEF={USA:'Highest costs, but assistantships can offset them. The visa interview is the key gate.',UK:'One-year masters save time and money. Plan the NHS surcharge and housing early.',Canada:'Strong post-study pathways, but rules change often. Check IRCC for current funds and work rules.',Germany:'Public universities charge low or no tuition. Living costs, the blocked account and teaching language matter.',Australia:'Work rights help, but GTE and health cover are essential.',Ireland:'English-speaking and tech-heavy. Housing is the real challenge.',France:'Public fees are modest. Language skills open far more doors.',Netherlands:'Many English programmes. Housing is competitive in big cities.',Singapore:'High quality, high cost, strong industry links. Competitive admissions.',UAE:'Fast-growing hub with branch campuses. Compare accreditation carefully.'};
const CSTEP={Germany:['Research the blocked account and APS requirements','coin'],UK:['Understand CAS and funds evidence for the Student visa','file'],USA:['Prepare for the I-20 and F-1 visa interview','file'],Canada:['Plan proof of funds and your study permit','file'],Australia:['Prepare your GTE statement and health cover','file']};
function plan(p){const c=p.c,st=p.stage,L=[],add=(id,t,i,go,w)=>L.push({id,t,i,go,w}),early=['Exploring','Preparing for exams'].includes(st),late=st=='Holding offers';
 if(early)add('sl',`Shortlist universities in ${c} for ${p.fld}`,'target','t:sch','Fit beats prestige. Budget and course content come first.');
 if(p.test=='Not taken yet')add('te','Book and clear your English test','book','t:ielts','Most offers depend on it, and slots fill up.');
 else if(p.test=='IELTS'&&p.ts<6.5)add('te','Lift your IELTS band before applying','book','t:ielts','Many masters programmes ask for 6.5 or more.');
 if(!late){add('sop',`Draft your ${p.fld} statement of purpose`,'pen','v:stories','Show why this programme, with specifics.');add('lor','Line up your recommenders','users','v:sen','Ask early and give them your résumé and goals.')}
 const f=p.fund;add('fund',f=='Education loan'?'Compare education loans and secure sanction':f=='Scholarship needed'?`Shortlist scholarships for ${c}`:f=='A mix'?'Build a funding plan: savings, loan, scholarships':'Document your family funds trail','coin',f=='Scholarship needed'?'t:sch':'t:cost','Funding evidence is checked at every stage.');
 if(p.cons&&p.cons!='No')add('flag','Run the red-flag check on your agent','shield','t:flag','Never pay before you have verified the terms in writing.');
 if(CSTEP[c])add('cs',CSTEP[c][0],CSTEP[c][1],'t:docs','Country rules change. Verify on the official government site.');
 if((p.topics||[]).includes('Part-time work'))add('pt',`Learn the work-hour rules in ${c}`,'bag','v:com','Rules differ by visa and course.');
 if((p.topics||[]).includes('Accommodation'))add('ho','Shortlist housing before you land','home','v:market','Never wire a deposit before a live tour.');
 add('visa','Prepare your visa file','globe','t:docs','Start collecting documents months ahead.');
 add('sen',`Talk to an Abrovia Senior in ${c}`,'chat','v:sen','Real experience beats brochures.');
 return L.slice(0,10)}
const go=g=>{const[a,b]=g.split(':');if(a=='v')nav(b);else{A.view='tools';render();tool(b)}};
const SCH=[['Chevening','UK',"Master's",'UK government award for future leaders on a one-year master’s.'],['DAAD EPOS','Germany',"Master's / PhD",'Germany’s flagship award for students from developing countries.'],['Fulbright-Nehru','USA',"Master's / PhD",'Fellowships for Indian students to study in the USA.'],['Commonwealth','UK',"Master's / PhD",'Funded study for students from Commonwealth countries.'],['Inlaks Shivdasani','Any',"Master's",'Private foundation award for Indian graduates at top universities.'],['JN Tata Endowment','Any',"Master's / PhD",'Loan-scholarship for Indian students pursuing higher studies abroad.'],['KC Mahindra','Any',"Master's",'Scholarship support for postgraduate study abroad.'],['National Overseas Scholarship','Any',"Master's / PhD",'Government scheme for eligible Indian students.'],['Erasmus Mundus','France / Netherlands / Europe',"Master's",'Joint masters across several European universities.']];
const TL=[['cost','calc','Cost Calculator','Total cost of attendance'],['bud','coin','Monthly Budget Planner','Plan your life abroad'],['cgpa','scale','CGPA Converter','Rough 4.0-scale estimate'],['ielts','book','IELTS Estimator','Typical band by level'],['cmp','scale','Offer Comparison','Compare two offers'],['flag','shield','Red-Flag Check','Score any agent offer'],['dl','clock','Deadline Planner','Countdown and weekly pace'],['docs','file','Document Checklist','By country'],['sch','trophy','Scholarship Finder','Real schemes, filterable'],['tl','cal','Intake Timeline','Month by month']];
const GUIDES=[['g_uk','book','UK Study Guide','UCAS, student visa and living costs.'],['g_de','book','Germany Free Tuition Guide','How to study at top German universities for little or nothing.'],['g_sb','trophy','Scholarship Bible','Curated scholarships for international students.'],['g_au','book','Australia Student Visa','Subclass 500 explained step by step.'],['g_ca','book','Canada PGWP and PR Guide','Post-study work rights and pathways.'],['g_lor','pen','LOR Writing Masterclass','Letters of recommendation that work.'],['t_sop','pen','SOP Builder','Generate a strong SOP outline in minutes.'],['t_uni','target','Uni Shortlister','A personalised Dream, Match and Safe list.']].map(x=>({k:x[0],i:x[1],n:x[2],d:x[3],st:'IN THE WORKS',pr:30+(x[0].length*7)%45,f:['Written by students who walked the path','Zero commission, zero bias','Free for every Abrovian']}));
const I=(id,p,t)=>`<input id="${id}" type="${t||'number'}" placeholder="${p}">`,T2=(a,b,c)=>`<h3>${a}</h3><div class="grid" style="margin:14px 0">${b}</div>${c}`;
function tool(k){
 if(A.view!='tools'){A.view='tools';render()}if(tv!='tools'){tv='tools';tools()}
 const h={
 cost:()=>T2('Cost Calculator',I('a','Yearly tuition (Rs)')+I('b','Monthly living (Rs)')+I('c','Years'),`<button class="btn" onclick="const t=((+a.value||0)+(+b.value||0)*12)*(+c.value||1);o.innerHTML='Estimated total: <b>Rs '+t.toLocaleString('en-IN')+'</b>. With a 10% buffer: <b>Rs '+Math.round(t*1.1).toLocaleString('en-IN')+'</b>'">Calculate</button><p id="o" style="margin-top:12px"></p>`),
 bud:()=>T2('Monthly Budget Planner',I('r1','Rent')+I('r2','Food')+I('r3','Transport')+I('r4','Phone and internet')+I('r5','Other'),`<button class="btn" onclick="const t=[1,2,3,4,5].reduce((s,i)=>s+(+document.getElementById('r'+i).value||0),0);o.innerHTML='Monthly: <b>'+t.toLocaleString('en-IN')+'</b>. Yearly: <b>'+(t*12).toLocaleString('en-IN')+'</b>. Keep a 10% buffer for surprises.'">Plan</button><p id="o" style="margin-top:12px"></p>`),
 cgpa:()=>T2('CGPA Converter',I('g1','CGPA out of 10'),`<button class="btn" onclick="const g=+g1.value;o.innerHTML=(g>0&&g<=10)?'Rough US 4.0 scale: <b>'+(g/10*4).toFixed(2)+'</b>. Approximate only. Universities and evaluation services use their own rules.':'<span class=\\'nt e\\'>Enter a CGPA between 0 and 10.</span>'">Convert</button><p id="o" style="margin-top:12px"></p>`),
 ielts:()=>`<h3>IELTS Estimator</h3><div class="fld" style="margin-top:12px"><select id="il" onchange="o.innerHTML=this.value?'Typical overall requirement: <b>'+this.value+'</b>. Each section is often at least 6.0. Always confirm on your university page.':''"><option value="">Select level</option><option>6.0 to 6.5</option><option>6.5 to 7.0</option><option>7.0 to 7.5</option></select></div><p class="mu">Bachelor: 6.0 to 6.5 · Master and MBA: 6.5 to 7.0 · Medicine, nursing, law: 7.0 to 7.5.</p><p id="o" style="margin-top:12px"></p>`,
 cmp:()=>T2('Offer Comparison',['A','B'].map(x=>I('t'+x,'Offer '+x+': yearly tuition')+I('l'+x,'Offer '+x+': yearly living')+I('s'+x,'Offer '+x+': yearly scholarship')+I('p'+x,'Offer '+x+': expected starting salary')).join(''),`<button class="btn" onclick="cmp()">Compare</button><div id="o" style="margin-top:12px"></div>`),
 flag:()=>`<h3>Red-Flag Check</h3><p class="mu" style="margin:4px 0 12px">Tick everything your agent has done.</p>${FLAGS.map(f=>`<label class="row" style="padding:5px 0"><input type="checkbox" class="fl" style="width:16px" onchange="fg()">${f}</label>`).join('')}<div id="fo" class="nt i" style="margin-top:12px">No red flags identified.</div>`,
 dl:()=>T2('Deadline Planner',I('d1','Deadline','date'),`<button class="btn" onclick="const d=Math.ceil((new Date(d1.value)-new Date())/864e5);o.innerHTML=isNaN(d)?'Pick a date.':d<0?'That date has passed.':'<b>'+d+' days</b> left. Aim to finish about <b>'+Math.max(1,Math.floor(d/7)-1)+' weeks</b> from now so you keep a buffer.'">Count down</button><p id="o" style="margin-top:12px"></p>`),
 docs:()=>`<h3>Document Checklist</h3><div class="fld" style="margin-top:12px"><select onchange="dcs(this.value)"><option value="">Select country</option>${COUNTRIES.map(c=>`<option>${c}</option>`).join('')}</select></div><div id="o"></div>`,
 sch:()=>`<h3>Scholarship Finder</h3><div class="fld" style="margin-top:12px"><select onchange="scs(this.value)"><option value="">All destinations</option>${COUNTRIES.map(c=>`<option>${c}</option>`).join('')}</select></div><div id="o">${scList('')}</div><p class="mu" style="margin-top:10px">Always confirm eligibility and deadlines on the official scholarship website.</p>`,
 tl:()=>`<h3>Intake Timeline</h3><div class="tl" style="margin-top:16px">${[['12 months before','Research, budget and shortlist'],['10 months','Language and aptitude exams'],['8 months','SOP and recommendation letters'],['6 months','Submit applications'],['3 months','Offers, loan sanction, visa'],['1 month','Housing, forex, travel']].map(x=>`<div><b>${x[0]}</b><div class="mu">${x[1]}</div></div>`).join('')}</div>`}[k]();
 $('#tool').innerHTML=`<div class="card" style="background:#fff">${h}</div>`;$('#tool').scrollIntoView({behavior:'smooth'})}
const scList=c=>SCH.filter(s=>!c||s[1]==c||s[1]=='Any'||s[1].includes(c)).map(s=>`<div class="row sp" style="padding:10px 0;border-bottom:1px solid var(--bd)"><div><b>${s[0]}</b><div class="mu">${s[3]}</div></div><span class="tag">${s[1]}</span></div>`).join('');
const scs=c=>{$('#o').innerHTML=scList(c)};
function dcs(c){const base=['Valid passport','Academic transcripts and degree','Language test score','Statement of purpose','Recommendation letters','CV','Proof of funds','Passport photos'],X={USA:['I-20 form','DS-160 confirmation','SEVIS fee receipt'],UK:['CAS statement','TB test certificate where required','Financial evidence held for the required period'],Canada:['Letter of acceptance','Proof of funds','Study permit application'],Germany:['Admission letter','Blocked account proof','Health insurance','APS certificate if required'],Australia:['Confirmation of Enrolment','GTE statement','Health cover']};$('#o').innerHTML=c?`<div style="margin-top:12px">${[...base,...(X[c]||['Residence permit documents'])].map(x=>`<label class="row" style="padding:4px 0"><input type="checkbox" style="width:16px">${x}</label>`).join('')}</div><p class="mu">Requirements change. Verify on the official immigration website.</p>`:''}
const FLAGS=['Promises guaranteed visa or admission','Demands a large upfront payment','No written agreement or receipt','Pushes a single country or university','Will not name partner universities','Pressures you to decide immediately','Suggests hiding or altering documents','Charges for free applications'];
function fg(){const n=document.querySelectorAll('.fl:checked').length;$('#fo').className='nt '+(n>=4?'e':n>=2?'w':'i');$('#fo').innerHTML=n>=4?'High risk. Do not pay. Ask in Consultancy Watch.':n>=2?'Moderate risk. Demand written terms and a refund clause.':n==1?'One flag is still a flag. Proceed with caution.':'No red flags identified.'}
function cmp(){const v=(k,x)=>+$('#'+k+x).value||0,r=['A','B'].map(x=>({x,net:v('t',x)+v('l',x)-v('s',x),sal:v('p',x)}));r.forEach(o=>o.roi=o.net>0?(o.sal/o.net).toFixed(2):'n/a');$('#o').innerHTML=r.map(o=>`<div class="row sp" style="padding:6px 0;border-bottom:1px solid var(--bd)"><b>Offer ${o.x}</b><span>Net yearly cost Rs ${o.net.toLocaleString('en-IN')} · salary to cost ${o.roi}x</span></div>`).join('')+'<p class="mu" style="margin-top:8px">A higher ratio means faster payback.</p>'}
const LAB=[['ai','spark','Abro AI','Your brutally honest co-pilot. No commission bias, no upselling.','BUILDING',70,['Profile-matched Dream, Match and Safe shortlist','Scholarship matching you are eligible for','SOP and LOR review with specific feedback','Country-by-country visa guidance']],
['space','users','Abrospace Network','The student network, decentralised. Profiles, groups and mentors in one place.','BUILDING',55,['Student profiles','Peer mentorship','Verified communities']],
['track','target','Live Application Tracker','Every application, deadline and document in one view.','DESIGNING',35,['Status per university','Deadline nudges','Document readiness']],
['vault','lock','Visa Document Vault','A secure place for every visa document, always ready.','DESIGNING',25,['Encrypted storage','Country checklists','Expiry reminders']],
['alum','award','Verified Alumni Network','Alumni verified by Abrovia, ready to guide you.','PLANNED',20,['Verified badges','Career pathways','Alumni Q&A']],
['uni','cap','University Partnerships','Transparent partnerships with zero commission to Abrovia.','PLANNED',15,['Direct admissions help','Fee transparency','Student-first terms']],
['app','plane','Abro Mobile App','Everything in your pocket, wherever you land.','PLANNED',15,['Offline checklists','Push reminders','Chat on the go']]].map(x=>({k:x[0],i:x[1],n:x[2],d:x[3],st:x[4],pr:x[5],f:x[6]}));
const ACAD=[['c1','IELTS Fundamentals'],['c2','GRE Quant Bootcamp'],['c3','SOP Writing Lab'],['c4','Visa Interview Practice']].map(x=>({k:x[0],i:'cap',n:x[1],d:'Free course by Abrovia Seniors.',st:'COMING SOON',pr:20,f:['Short video lessons','Practice questions','Feedback from Seniors']}));
